name: exllama-docker

on:
  workflow_dispatch:
    inputs:
      branchName:
        description: 'Branch Name' # Description of the input
        required: true # This input needs to be provided when triggering the workflow
  release:
    types: [ published ] # Run this workflow when a release is published

jobs:
  exllama-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GHCR_TOKEN }}
          submodules: recursive
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64
          context: .
          file: ./Dockerfile
          tags: ghcr.io/vendi-ai/runpod-serverless-exllama/worker:latest
          build-args: |
            HUGGING_FACE_HUB_TOKEN=${{ secrets.HUGGING_FACE_HUB_TOKEN }}
